spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  override-with-generic-response: false

welfare:
  api:
    base-url: http://apis.data.go.kr/B554287/LocalGovernmentWelfareInformations
    service-key: ${WELFARE_API_SERVICE_KEY}