package salpim.umc10thsalpim.domain.auth.exception.code;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;
import salpim.umc10thsalpim.global.apiPayload.code.BaseErrorCode;

@Getter
@AllArgsConstructor
public enum AuthErrorCode implements BaseErrorCode {

    LOGIN_MEMBER_NOT_FOUND(HttpStatus.NOT_FOUND,
            "AUTH404_LOGIN_MEMBER",
            "등록되지 않은 회원입니다."),
    INVALID_PASSWORD(HttpStatus.UNAUTHORIZED,
            "AUTH401_PASSWORD",
            "비밀번호가 일치하지 않습니다."),
    INVALID_LOGIN_CREDENTIALS(HttpStatus.UNAUTHORIZED,
            "AUTH401_LOGIN_CREDENTIALS",
            "전화번호 또는 비밀번호가 올바르지 않습니다."),
    INVALID_TOKEN(HttpStatus.UNAUTHORIZED,
            "AUTH401_TOKEN",
            "유효하지 않은 토큰입니다."),
    INVALID_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED,
            "AUTH401_REFRESH_TOKEN",
            "유효하지 않은 리프레시 토큰입니다."),
    EXPIRED_REFRESH_TOKEN(HttpStatus.UNAUTHORIZED,
            "AUTH401_REFRESH_TOKEN_EXPIRED",
            "리프레시 토큰이 만료되었습니다."),
    INVALID_VERIFICATION_CODE(HttpStatus.BAD_REQUEST,
            "AUTH400_VERIFICATION",
            "인증번호가 일치하지 않습니다."),
    EXPIRED_VERIFICATION_CODE(HttpStatus.BAD_REQUEST,
            "AUTH400_VERIFICATION_EXPIRED",
            "인증번호가 만료되었습니다."),
    PHONE_NOT_VERIFIED(HttpStatus.BAD_REQUEST,
            "AUTH400_PHONE_NOT_VERIFIED",
            "휴대폰 인증이 완료되지 않았습니다."),
    GEOCODING_RESULT_NOT_FOUND(HttpStatus.NOT_FOUND,
            "AUTH404_GEOCODING",
            "주소 검색 결과를 찾을 수 없습니다."),
    GEOCODING_API_ERROR(HttpStatus.BAD_GATEWAY,
            "AUTH502_GEOCODING",
            "주소 좌표 조회에 실패했습니다."),
    KAKAO_AUTHORIZATION_CODE_INVALID(HttpStatus.BAD_REQUEST,
            "AUTH400_KAKAO_CODE",
            "카카오 인가 코드가 유효하지 않습니다."),
    KAKAO_API_ERROR(HttpStatus.BAD_GATEWAY,
            "AUTH502_KAKAO",
            "카카오 API 요청에 실패했습니다."),
    KAKAO_USER_ID_MISSING(HttpStatus.BAD_GATEWAY,
            "AUTH502_KAKAO_ID",
            "카카오 사용자 식별자를 확인할 수 없습니다."),
    SIGNUP_TOKEN_INVALID(HttpStatus.UNAUTHORIZED,
            "AUTH401_SIGNUP_TOKEN",
            "유효하지 않은 회원가입 토큰입니다."),
    SIGNUP_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED,
            "AUTH401_SIGNUP_TOKEN_EXPIRED",
            "회원가입 토큰이 만료되었습니다."),
    SIGNUP_TOKEN_TYPE_INVALID(HttpStatus.UNAUTHORIZED,
            "AUTH401_SIGNUP_TOKEN_TYPE",
            "회원가입 토큰이 아닙니다."),
    PHONE_CHANGE_REQUEST_INVALID(HttpStatus.BAD_REQUEST,
            "AUTH400_PHONE_CHANGE_REQUEST",
            "전화번호와 인증 토큰은 함께 입력해야 합니다."),
    INVALID_PHONE_VERIFICATION_TOKEN(HttpStatus.BAD_REQUEST,
            "AUTH400_PHONE_VERIFICATION_TOKEN",
            "유효하지 않은 전화번호 변경 인증 토큰입니다."),
    EXPIRED_PHONE_VERIFICATION_TOKEN(HttpStatus.BAD_REQUEST,
            "AUTH400_PHONE_VERIFICATION_TOKEN_EXPIRED",
            "전화번호 변경 인증 토큰이 만료되었습니다."),
    PHONE_VERIFICATION_RESEND_TOO_SOON(HttpStatus.TOO_MANY_REQUESTS,
            "AUTH429_PHONE_VERIFICATION_RESEND",
            "인증번호는 1분 후에 다시 요청할 수 있습니다."),
    PHONE_VERIFICATION_ATTEMPTS_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS,
            "AUTH429_PHONE_VERIFICATION_ATTEMPTS",
            "인증번호 검증 시도 횟수를 초과했습니다. 잠시 후 다시 시도해 주세요."),
    PASSWORD_RESET_TOKEN_INVALID(HttpStatus.UNAUTHORIZED,
            "AUTH401_PASSWORD_RESET_TOKEN",
            "유효하지 않은 비밀번호 초기화 인증 토큰입니다."),
    PASSWORD_RESET_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED,
            "AUTH401_PASSWORD_RESET_TOKEN_EXPIRED",
            "비밀번호 초기화 인증 토큰이 만료되었습니다."),
    PASSWORD_RESET_TOKEN_TYPE_INVALID(HttpStatus.UNAUTHORIZED,
            "AUTH401_PASSWORD_RESET_TOKEN_TYPE",
            "비밀번호 초기화 토큰이 아닙니다."),
    PASSWORD_RESET_VERIFICATION_FAILED(HttpStatus.BAD_REQUEST,
            "AUTH400_PASSWORD_RESET_VERIFICATION",
            "전화번호 또는 비밀번호 복구 답변이 일치하지 않습니다."),
    PASSWORD_VERIFICATION_ATTEMPTS_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS,
            "AUTH429_PASSWORD_VERIFICATION_ATTEMPTS",
            "비밀번호 검증 시도 횟수를 초과했습니다. 잠시 후 다시 시도해주세요."),
    SMS_SEND_FAILED(HttpStatus.BAD_GATEWAY,
            "AUTH502_SMS_SEND",
            "인증번호 문자 발송에 실패했습니다."),
    ;

    private final HttpStatus status;
    private final String code;
    private final String message;
}
